Traceback (most recent call last):
  File "/home/daril/trajcbert/testing_1_point.py", line 46, in <module>
    model = BertForSequenceClassification.from_pretrained(PRETRAINED_MODEL_NAME)
  File "/localscratch/daril.20297971.0/MYENV/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2325, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/localscratch/daril.20297971.0/MYENV/lib/python3.10/site-packages/transformers/configuration_utils.py", line 590, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/localscratch/daril.20297971.0/MYENV/lib/python3.10/site-packages/transformers/configuration_utils.py", line 617, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/localscratch/daril.20297971.0/MYENV/lib/python3.10/site-packages/transformers/configuration_utils.py", line 672, in _get_config_dict
    resolved_config_file = cached_file(
  File "/localscratch/daril.20297971.0/MYENV/lib/python3.10/site-packages/transformers/utils/hub.py", line 388, in cached_file
    raise EnvironmentError(
OSError: /home/daril/trajcbert//home/daril/scratch/data/trajcbert/models/model_saved_parallel_version_1_2_32 does not appear to have a file named config.json. Checkout 'https://huggingface.co//home/daril/trajcbert//home/daril/scratch/data/trajcbert/models/model_saved_parallel_version_1_2_32/main' for available files.
